development:
  adapter: mysql2
  database: ov_dev
  username: ov_dev
  password: ov_dev

test:
  adapter: mysql2
  database: ov_test
  username: ov_test
  password: ov_test
  encoding: utf8
  
production:
  adapter: mysql2
  database: ov_dev
  username: ov_dev
  password: ov_dev